_wandb:
    value:
        cli_version: 0.21.0
        e:
            r0sp0boefalu2g9wz1ak2vplegg5xw15:
                codePath: Transfer_v4_RMa.py
                codePathLocal: Transfer_v4_RMa.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "42949672960"
                        used: "319131648"
                email: joowonoil@g.skku.edu
                executable: /opt/conda/bin/python
                git:
                    commit: 065815abc548776d1970d9c7eaca92ac955de97e
                    remote: https://github.com/Joowonoil/channel-estimation-training-RMa.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-99ad11d5-b87b-e343-b712-6f014195bc1a
                host: 45af7c9bf546
                memory:
                    total: "2151669825536"
                os: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
                program: /root/channel-estimation-training-RMa/Transfer_v4_RMa.py
                python: CPython 3.11.9
                root: /root/channel-estimation-training-RMa
                startedAt: "2025-08-04T09:52:59.028625Z"
                writerId: r0sp0boefalu2g9wz1ak2vplegg5xw15
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "3":
                - 16
            "4": 3.11.9
            "5": 0.21.0
            "6": 4.54.1
            "12": 0.21.0
            "13": linux-x86_64
ch_estimation:
    value:
        cond:
            in_channels: 2
            length: 3072
            step_size: 12
            steps_per_token: 1
        peft:
            lora_alpha: 8
            lora_dropout: 0.1
            peft_type: LORA
            r: 8
            target_modules:
                - mha_q_proj
                - mha_k_proj
                - mha_v_proj
                - out_proj
                - ffnn_linear1
                - ffnn_linear2
        transformer:
            activation: relu
            channels: 2
            d_model: 128
            dim_feedforward: 1024
            dropout: 0.1
            length: 3072
            n_head: 8
            n_token: 256
            num_layers: 4
dataset:
    value:
        batch_size: 32
        carrier_freq: 28
        channel_type:
            - RMa_Los_50000
        cp_length: 590
        distance_range:
            - 10
            - 500
        fft_size: 4096
        is_channel: true
        is_noise: true
        is_phase_noise: false
        max_random_tap_delay_cp_proportion: 0.2
        mod_order: 64
        noise_spectral_density: -174
        num_guard_subcarriers: 1024
        num_symbol: 14
        num_workers: 0
        ref_conf_dict:
            dmrs:
                - 0
                - 3072
                - 6
        rnd_seed: 0
        subcarrier_spacing: 120
        transmit_power: 30
training:
    value:
        ch_loss_weight: 1
        checkpoint_path: saved_model/checkpoint_v4_RMa.pt
        device: cuda:0
        early_stopping_verbose: true
        evaluation_batch_size: 4
        evaluation_step: 1000
        load_model_path: ""
        logging_step: 10
        lr: 1e-05
        max_norm: 1
        model_load_mode: pretrained
        model_save_step: 100000
        num_freeze_layers: 0
        num_iter: 200000
        num_warmup_steps: 0
        pn_train_start_iter: 50000
        pretrained_model_name: Large_estimator_PreLN
        saved_model_name: Large_estimator_PreLN_2_RMa
        use_early_stopping: false
        use_scheduler: true
        use_wandb: true
        wandb_proj: DNN_channel_estimation_RMa_LoRA_Transfer
        weight_decay: 1e-06
